###############################################################################
#
#                                 AUTOMATIONS
#
###############################################################################
  - alias: "Spegne il pc in caso salti la luce e manda una notifica"
    trigger:
      - platform: state
        entity_id: binary_sensor.zidoo
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.computersalotto
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.windows
      - service: notify.notify
        data:
          message: "E' saltata la luce."
#dopo tot minuti spegnere hassio
#******************************************************************************
  - alias: "Restart HA during the weekdays"
    trigger: 
      platform: time
      at: "16:30:00"
    condition:
      condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    action:
      - service: notify.notify
        data:
          message: "Home Assistant in riavvio automatico giornaliero."
      - service: homeassistant.restart
#******************************************************************************
  - alias: "Restart HA during the weekend"
    trigger: 
      platform: time
      at: "08:00:00"
    condition:
      condition: time
      weekday:
      - sat
      - sun
    action:
      - service: homeassistant.restart
#******************************************************************************
  - alias: Startup Notification
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: notify.notify
        data:
          message: "Home Assistant è attivo."
      - service: hassio.addon_stdin
        data:
          addon: de3cd379_audio_player
          input: "http://192.168.1.100:8123/local/computer_activate.mp3"
      - service: group.set_visibility
        entity_id: group.airconditioner
        data:
          visible: False
      - service: group.set_visibility
        entity_id: group.termoventilatore_bagno
        data:
          visible: False
      - service: group.set_visibility
        entity_id: group.media_salotto
        data:
          visible: False
      - service: group.set_visibility
        entity_id: group.radio
        data:
          visible: False
      - service: group.set_visibility
        entity_id: group.telecomando_tv
        data:
          visible: False
      - service: group.set_visibility
        entity_id: group.tastierino_sky
        data:
          visible: False
      - service: group.set_visibility
        entity_id: group.telecomando_sky
        data:
          visible: False
      - service: group.set_visibility
        entity_id: group.dash_buttons
        data:
          visible: False
      - service: google_assistant.request_sync
#******************************************************************************
  - alias: "Shutdown/Reboot Notification"
    trigger:
      - platform: homeassistant
        event: shutdown
    action:
      - service: notify.notify
        data:
          message: "Home Assistant è in riavvio."
      - service: hassio.addon_stdin
        data:
          addon: de3cd379_audio_player
          input: "http://192.168.1.100:8123/local/hologram_off.mp3"
#******************************************************************************